language: swift
sudo: true
osx_image: xcode10.1
xcode_project: Step Counting Application.xcodeproj
xcode_scheme: Step Counting Application
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
after_success:
- curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge
- chmod a+x /tmp/travis-automerge
- BRANCHES_TO_MERGE_REGEX='^f/' BRANCH_TO_MERGE_INTO=develop GITHUB_REPO=cdown/srt
  /tmp/travis-automerge
